// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250820181330_SeedEmployeeDataModel")]
    partial class SeedEmployeeDataModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("API.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .HasColumnType("longtext");

                    b.Property<string>("Designation")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "Sales",
                            Designation = "Manager",
                            Email = "john@example.com",
                            JoiningDate = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "John Doe",
                            Salary = 75000m
                        },
                        new
                        {
                            Id = 2,
                            Department = "IT",
                            Designation = "Developer",
                            Email = "jane@example.com",
                            JoiningDate = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jane Smith",
                            Salary = 65000m
                        },
                        new
                        {
                            Id = 3,
                            Department = "Marketing",
                            Designation = "Designer",
                            Email = "alice@example.com",
                            JoiningDate = new DateTime(2020, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Alice Johnson",
                            Salary = 60000m
                        },
                        new
                        {
                            Id = 4,
                            Department = "Customer Service",
                            Designation = "Support",
                            Email = "bob@example.com",
                            JoiningDate = new DateTime(2019, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bob Brown",
                            Salary = 50000m
                        },
                        new
                        {
                            Id = 5,
                            Department = "Human Resources",
                            Designation = "HR",
                            Email = "charlie@example.com",
                            JoiningDate = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Charlie Lee",
                            Salary = 70000m
                        },
                        new
                        {
                            Id = 6,
                            Department = "Finance",
                            Designation = "Accountant",
                            Email = "eva@example.com",
                            JoiningDate = new DateTime(2022, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Eva Green",
                            Salary = 68000m
                        },
                        new
                        {
                            Id = 7,
                            Department = "Business",
                            Designation = "Analyst",
                            Email = "frank@example.com",
                            JoiningDate = new DateTime(2021, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Frank White",
                            Salary = 72000m
                        },
                        new
                        {
                            Id = 8,
                            Department = "Consulting",
                            Designation = "Consultant",
                            Email = "grace@example.com",
                            JoiningDate = new DateTime(2020, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Grace Black",
                            Salary = 80000m
                        },
                        new
                        {
                            Id = 9,
                            Department = "IT",
                            Designation = "Intern",
                            Email = "henry@example.com",
                            JoiningDate = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Henry King",
                            Salary = 35000m
                        },
                        new
                        {
                            Id = 10,
                            Department = "Operations",
                            Designation = "Lead",
                            Email = "ivy@example.com",
                            JoiningDate = new DateTime(2018, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ivy Queen",
                            Salary = 90000m
                        });
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
