// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("API.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .HasColumnType("longtext");

                    b.Property<string>("Designation")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "IT",
                            Designation = "Developer",
                            Email = "employee1@example.com",
                            JoiningDate = new DateTime(2020, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 1",
                            Salary = 40500m
                        },
                        new
                        {
                            Id = 2,
                            Department = "Marketing",
                            Designation = "Designer",
                            Email = "employee2@example.com",
                            JoiningDate = new DateTime(2020, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 2",
                            Salary = 41000m
                        },
                        new
                        {
                            Id = 3,
                            Department = "Customer Service",
                            Designation = "Support",
                            Email = "employee3@example.com",
                            JoiningDate = new DateTime(2020, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 3",
                            Salary = 41500m
                        },
                        new
                        {
                            Id = 4,
                            Department = "Human Resources",
                            Designation = "HR",
                            Email = "employee4@example.com",
                            JoiningDate = new DateTime(2020, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 4",
                            Salary = 42000m
                        },
                        new
                        {
                            Id = 5,
                            Department = "Finance",
                            Designation = "Accountant",
                            Email = "employee5@example.com",
                            JoiningDate = new DateTime(2020, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 5",
                            Salary = 42500m
                        },
                        new
                        {
                            Id = 6,
                            Department = "Business",
                            Designation = "Analyst",
                            Email = "employee6@example.com",
                            JoiningDate = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 6",
                            Salary = 43000m
                        },
                        new
                        {
                            Id = 7,
                            Department = "Consulting",
                            Designation = "Consultant",
                            Email = "employee7@example.com",
                            JoiningDate = new DateTime(2020, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 7",
                            Salary = 43500m
                        },
                        new
                        {
                            Id = 8,
                            Department = "Operations",
                            Designation = "Intern",
                            Email = "employee8@example.com",
                            JoiningDate = new DateTime(2020, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 8",
                            Salary = 44000m
                        },
                        new
                        {
                            Id = 9,
                            Department = "Sales",
                            Designation = "Lead",
                            Email = "employee9@example.com",
                            JoiningDate = new DateTime(2020, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 9",
                            Salary = 44500m
                        },
                        new
                        {
                            Id = 10,
                            Department = "IT",
                            Designation = "Manager",
                            Email = "employee10@example.com",
                            JoiningDate = new DateTime(2020, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 10",
                            Salary = 45000m
                        },
                        new
                        {
                            Id = 11,
                            Department = "Marketing",
                            Designation = "Developer",
                            Email = "employee11@example.com",
                            JoiningDate = new DateTime(2020, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 11",
                            Salary = 45500m
                        },
                        new
                        {
                            Id = 12,
                            Department = "Customer Service",
                            Designation = "Designer",
                            Email = "employee12@example.com",
                            JoiningDate = new DateTime(2020, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 12",
                            Salary = 46000m
                        },
                        new
                        {
                            Id = 13,
                            Department = "Human Resources",
                            Designation = "Support",
                            Email = "employee13@example.com",
                            JoiningDate = new DateTime(2020, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 13",
                            Salary = 46500m
                        },
                        new
                        {
                            Id = 14,
                            Department = "Finance",
                            Designation = "HR",
                            Email = "employee14@example.com",
                            JoiningDate = new DateTime(2020, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 14",
                            Salary = 47000m
                        },
                        new
                        {
                            Id = 15,
                            Department = "Business",
                            Designation = "Accountant",
                            Email = "employee15@example.com",
                            JoiningDate = new DateTime(2020, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 15",
                            Salary = 47500m
                        },
                        new
                        {
                            Id = 16,
                            Department = "Consulting",
                            Designation = "Analyst",
                            Email = "employee16@example.com",
                            JoiningDate = new DateTime(2020, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 16",
                            Salary = 48000m
                        },
                        new
                        {
                            Id = 17,
                            Department = "Operations",
                            Designation = "Consultant",
                            Email = "employee17@example.com",
                            JoiningDate = new DateTime(2020, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 17",
                            Salary = 48500m
                        },
                        new
                        {
                            Id = 18,
                            Department = "Sales",
                            Designation = "Intern",
                            Email = "employee18@example.com",
                            JoiningDate = new DateTime(2020, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 18",
                            Salary = 49000m
                        },
                        new
                        {
                            Id = 19,
                            Department = "IT",
                            Designation = "Lead",
                            Email = "employee19@example.com",
                            JoiningDate = new DateTime(2020, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 19",
                            Salary = 49500m
                        },
                        new
                        {
                            Id = 20,
                            Department = "Marketing",
                            Designation = "Manager",
                            Email = "employee20@example.com",
                            JoiningDate = new DateTime(2020, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 20",
                            Salary = 50000m
                        },
                        new
                        {
                            Id = 21,
                            Department = "Customer Service",
                            Designation = "Developer",
                            Email = "employee21@example.com",
                            JoiningDate = new DateTime(2020, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 21",
                            Salary = 50500m
                        },
                        new
                        {
                            Id = 22,
                            Department = "Human Resources",
                            Designation = "Designer",
                            Email = "employee22@example.com",
                            JoiningDate = new DateTime(2020, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 22",
                            Salary = 51000m
                        },
                        new
                        {
                            Id = 23,
                            Department = "Finance",
                            Designation = "Support",
                            Email = "employee23@example.com",
                            JoiningDate = new DateTime(2020, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 23",
                            Salary = 51500m
                        },
                        new
                        {
                            Id = 24,
                            Department = "Business",
                            Designation = "HR",
                            Email = "employee24@example.com",
                            JoiningDate = new DateTime(2020, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 24",
                            Salary = 52000m
                        },
                        new
                        {
                            Id = 25,
                            Department = "Consulting",
                            Designation = "Accountant",
                            Email = "employee25@example.com",
                            JoiningDate = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 25",
                            Salary = 52500m
                        },
                        new
                        {
                            Id = 26,
                            Department = "Operations",
                            Designation = "Analyst",
                            Email = "employee26@example.com",
                            JoiningDate = new DateTime(2020, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 26",
                            Salary = 53000m
                        },
                        new
                        {
                            Id = 27,
                            Department = "Sales",
                            Designation = "Consultant",
                            Email = "employee27@example.com",
                            JoiningDate = new DateTime(2020, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 27",
                            Salary = 53500m
                        },
                        new
                        {
                            Id = 28,
                            Department = "IT",
                            Designation = "Intern",
                            Email = "employee28@example.com",
                            JoiningDate = new DateTime(2020, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 28",
                            Salary = 54000m
                        },
                        new
                        {
                            Id = 29,
                            Department = "Marketing",
                            Designation = "Lead",
                            Email = "employee29@example.com",
                            JoiningDate = new DateTime(2020, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 29",
                            Salary = 54500m
                        },
                        new
                        {
                            Id = 30,
                            Department = "Customer Service",
                            Designation = "Manager",
                            Email = "employee30@example.com",
                            JoiningDate = new DateTime(2020, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 30",
                            Salary = 55000m
                        },
                        new
                        {
                            Id = 31,
                            Department = "Human Resources",
                            Designation = "Developer",
                            Email = "employee31@example.com",
                            JoiningDate = new DateTime(2020, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 31",
                            Salary = 55500m
                        },
                        new
                        {
                            Id = 32,
                            Department = "Finance",
                            Designation = "Designer",
                            Email = "employee32@example.com",
                            JoiningDate = new DateTime(2020, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 32",
                            Salary = 56000m
                        },
                        new
                        {
                            Id = 33,
                            Department = "Business",
                            Designation = "Support",
                            Email = "employee33@example.com",
                            JoiningDate = new DateTime(2020, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 33",
                            Salary = 56500m
                        },
                        new
                        {
                            Id = 34,
                            Department = "Consulting",
                            Designation = "HR",
                            Email = "employee34@example.com",
                            JoiningDate = new DateTime(2020, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 34",
                            Salary = 57000m
                        },
                        new
                        {
                            Id = 35,
                            Department = "Operations",
                            Designation = "Accountant",
                            Email = "employee35@example.com",
                            JoiningDate = new DateTime(2020, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 35",
                            Salary = 57500m
                        },
                        new
                        {
                            Id = 36,
                            Department = "Sales",
                            Designation = "Analyst",
                            Email = "employee36@example.com",
                            JoiningDate = new DateTime(2020, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 36",
                            Salary = 58000m
                        },
                        new
                        {
                            Id = 37,
                            Department = "IT",
                            Designation = "Consultant",
                            Email = "employee37@example.com",
                            JoiningDate = new DateTime(2021, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 37",
                            Salary = 58500m
                        },
                        new
                        {
                            Id = 38,
                            Department = "Marketing",
                            Designation = "Intern",
                            Email = "employee38@example.com",
                            JoiningDate = new DateTime(2021, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 38",
                            Salary = 59000m
                        },
                        new
                        {
                            Id = 39,
                            Department = "Customer Service",
                            Designation = "Lead",
                            Email = "employee39@example.com",
                            JoiningDate = new DateTime(2021, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 39",
                            Salary = 59500m
                        },
                        new
                        {
                            Id = 40,
                            Department = "Human Resources",
                            Designation = "Manager",
                            Email = "employee40@example.com",
                            JoiningDate = new DateTime(2021, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 40",
                            Salary = 60000m
                        },
                        new
                        {
                            Id = 41,
                            Department = "Finance",
                            Designation = "Developer",
                            Email = "employee41@example.com",
                            JoiningDate = new DateTime(2021, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 41",
                            Salary = 60500m
                        },
                        new
                        {
                            Id = 42,
                            Department = "Business",
                            Designation = "Designer",
                            Email = "employee42@example.com",
                            JoiningDate = new DateTime(2021, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 42",
                            Salary = 61000m
                        },
                        new
                        {
                            Id = 43,
                            Department = "Consulting",
                            Designation = "Support",
                            Email = "employee43@example.com",
                            JoiningDate = new DateTime(2021, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 43",
                            Salary = 61500m
                        },
                        new
                        {
                            Id = 44,
                            Department = "Operations",
                            Designation = "HR",
                            Email = "employee44@example.com",
                            JoiningDate = new DateTime(2021, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 44",
                            Salary = 62000m
                        },
                        new
                        {
                            Id = 45,
                            Department = "Sales",
                            Designation = "Accountant",
                            Email = "employee45@example.com",
                            JoiningDate = new DateTime(2021, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 45",
                            Salary = 62500m
                        },
                        new
                        {
                            Id = 46,
                            Department = "IT",
                            Designation = "Analyst",
                            Email = "employee46@example.com",
                            JoiningDate = new DateTime(2021, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 46",
                            Salary = 63000m
                        },
                        new
                        {
                            Id = 47,
                            Department = "Marketing",
                            Designation = "Consultant",
                            Email = "employee47@example.com",
                            JoiningDate = new DateTime(2021, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 47",
                            Salary = 63500m
                        },
                        new
                        {
                            Id = 48,
                            Department = "Customer Service",
                            Designation = "Intern",
                            Email = "employee48@example.com",
                            JoiningDate = new DateTime(2021, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 48",
                            Salary = 64000m
                        },
                        new
                        {
                            Id = 49,
                            Department = "Human Resources",
                            Designation = "Lead",
                            Email = "employee49@example.com",
                            JoiningDate = new DateTime(2021, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 49",
                            Salary = 64500m
                        },
                        new
                        {
                            Id = 50,
                            Department = "Finance",
                            Designation = "Manager",
                            Email = "employee50@example.com",
                            JoiningDate = new DateTime(2021, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 50",
                            Salary = 65000m
                        },
                        new
                        {
                            Id = 51,
                            Department = "Business",
                            Designation = "Developer",
                            Email = "employee51@example.com",
                            JoiningDate = new DateTime(2021, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 51",
                            Salary = 65500m
                        },
                        new
                        {
                            Id = 52,
                            Department = "Consulting",
                            Designation = "Designer",
                            Email = "employee52@example.com",
                            JoiningDate = new DateTime(2021, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 52",
                            Salary = 66000m
                        },
                        new
                        {
                            Id = 53,
                            Department = "Operations",
                            Designation = "Support",
                            Email = "employee53@example.com",
                            JoiningDate = new DateTime(2021, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 53",
                            Salary = 66500m
                        },
                        new
                        {
                            Id = 54,
                            Department = "Sales",
                            Designation = "HR",
                            Email = "employee54@example.com",
                            JoiningDate = new DateTime(2021, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 54",
                            Salary = 67000m
                        },
                        new
                        {
                            Id = 55,
                            Department = "IT",
                            Designation = "Accountant",
                            Email = "employee55@example.com",
                            JoiningDate = new DateTime(2021, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 55",
                            Salary = 67500m
                        },
                        new
                        {
                            Id = 56,
                            Department = "Marketing",
                            Designation = "Analyst",
                            Email = "employee56@example.com",
                            JoiningDate = new DateTime(2021, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 56",
                            Salary = 68000m
                        },
                        new
                        {
                            Id = 57,
                            Department = "Customer Service",
                            Designation = "Consultant",
                            Email = "employee57@example.com",
                            JoiningDate = new DateTime(2021, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 57",
                            Salary = 68500m
                        },
                        new
                        {
                            Id = 58,
                            Department = "Human Resources",
                            Designation = "Intern",
                            Email = "employee58@example.com",
                            JoiningDate = new DateTime(2021, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 58",
                            Salary = 69000m
                        },
                        new
                        {
                            Id = 59,
                            Department = "Finance",
                            Designation = "Lead",
                            Email = "employee59@example.com",
                            JoiningDate = new DateTime(2021, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 59",
                            Salary = 69500m
                        },
                        new
                        {
                            Id = 60,
                            Department = "Business",
                            Designation = "Manager",
                            Email = "employee60@example.com",
                            JoiningDate = new DateTime(2021, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 60",
                            Salary = 70000m
                        },
                        new
                        {
                            Id = 61,
                            Department = "Consulting",
                            Designation = "Developer",
                            Email = "employee61@example.com",
                            JoiningDate = new DateTime(2021, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 61",
                            Salary = 70500m
                        },
                        new
                        {
                            Id = 62,
                            Department = "Operations",
                            Designation = "Designer",
                            Email = "employee62@example.com",
                            JoiningDate = new DateTime(2021, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 62",
                            Salary = 71000m
                        },
                        new
                        {
                            Id = 63,
                            Department = "Sales",
                            Designation = "Support",
                            Email = "employee63@example.com",
                            JoiningDate = new DateTime(2021, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 63",
                            Salary = 71500m
                        },
                        new
                        {
                            Id = 64,
                            Department = "IT",
                            Designation = "HR",
                            Email = "employee64@example.com",
                            JoiningDate = new DateTime(2021, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 64",
                            Salary = 72000m
                        },
                        new
                        {
                            Id = 65,
                            Department = "Marketing",
                            Designation = "Accountant",
                            Email = "employee65@example.com",
                            JoiningDate = new DateTime(2021, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 65",
                            Salary = 72500m
                        },
                        new
                        {
                            Id = 66,
                            Department = "Customer Service",
                            Designation = "Analyst",
                            Email = "employee66@example.com",
                            JoiningDate = new DateTime(2021, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 66",
                            Salary = 73000m
                        },
                        new
                        {
                            Id = 67,
                            Department = "Human Resources",
                            Designation = "Consultant",
                            Email = "employee67@example.com",
                            JoiningDate = new DateTime(2021, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 67",
                            Salary = 73500m
                        },
                        new
                        {
                            Id = 68,
                            Department = "Finance",
                            Designation = "Intern",
                            Email = "employee68@example.com",
                            JoiningDate = new DateTime(2021, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 68",
                            Salary = 74000m
                        },
                        new
                        {
                            Id = 69,
                            Department = "Business",
                            Designation = "Lead",
                            Email = "employee69@example.com",
                            JoiningDate = new DateTime(2021, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 69",
                            Salary = 74500m
                        },
                        new
                        {
                            Id = 70,
                            Department = "Consulting",
                            Designation = "Manager",
                            Email = "employee70@example.com",
                            JoiningDate = new DateTime(2021, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 70",
                            Salary = 75000m
                        },
                        new
                        {
                            Id = 71,
                            Department = "Operations",
                            Designation = "Developer",
                            Email = "employee71@example.com",
                            JoiningDate = new DateTime(2021, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 71",
                            Salary = 75500m
                        },
                        new
                        {
                            Id = 72,
                            Department = "Sales",
                            Designation = "Designer",
                            Email = "employee72@example.com",
                            JoiningDate = new DateTime(2021, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 72",
                            Salary = 76000m
                        },
                        new
                        {
                            Id = 73,
                            Department = "IT",
                            Designation = "Support",
                            Email = "employee73@example.com",
                            JoiningDate = new DateTime(2021, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 73",
                            Salary = 76500m
                        },
                        new
                        {
                            Id = 74,
                            Department = "Marketing",
                            Designation = "HR",
                            Email = "employee74@example.com",
                            JoiningDate = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 74",
                            Salary = 77000m
                        },
                        new
                        {
                            Id = 75,
                            Department = "Customer Service",
                            Designation = "Accountant",
                            Email = "employee75@example.com",
                            JoiningDate = new DateTime(2022, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 75",
                            Salary = 77500m
                        },
                        new
                        {
                            Id = 76,
                            Department = "Human Resources",
                            Designation = "Analyst",
                            Email = "employee76@example.com",
                            JoiningDate = new DateTime(2022, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 76",
                            Salary = 78000m
                        },
                        new
                        {
                            Id = 77,
                            Department = "Finance",
                            Designation = "Consultant",
                            Email = "employee77@example.com",
                            JoiningDate = new DateTime(2022, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 77",
                            Salary = 78500m
                        },
                        new
                        {
                            Id = 78,
                            Department = "Business",
                            Designation = "Intern",
                            Email = "employee78@example.com",
                            JoiningDate = new DateTime(2022, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 78",
                            Salary = 79000m
                        },
                        new
                        {
                            Id = 79,
                            Department = "Consulting",
                            Designation = "Lead",
                            Email = "employee79@example.com",
                            JoiningDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 79",
                            Salary = 79500m
                        },
                        new
                        {
                            Id = 80,
                            Department = "Operations",
                            Designation = "Manager",
                            Email = "employee80@example.com",
                            JoiningDate = new DateTime(2022, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 80",
                            Salary = 80000m
                        },
                        new
                        {
                            Id = 81,
                            Department = "Sales",
                            Designation = "Developer",
                            Email = "employee81@example.com",
                            JoiningDate = new DateTime(2022, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 81",
                            Salary = 80500m
                        },
                        new
                        {
                            Id = 82,
                            Department = "IT",
                            Designation = "Designer",
                            Email = "employee82@example.com",
                            JoiningDate = new DateTime(2022, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 82",
                            Salary = 81000m
                        },
                        new
                        {
                            Id = 83,
                            Department = "Marketing",
                            Designation = "Support",
                            Email = "employee83@example.com",
                            JoiningDate = new DateTime(2022, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 83",
                            Salary = 81500m
                        },
                        new
                        {
                            Id = 84,
                            Department = "Customer Service",
                            Designation = "HR",
                            Email = "employee84@example.com",
                            JoiningDate = new DateTime(2022, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 84",
                            Salary = 82000m
                        },
                        new
                        {
                            Id = 85,
                            Department = "Human Resources",
                            Designation = "Accountant",
                            Email = "employee85@example.com",
                            JoiningDate = new DateTime(2022, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 85",
                            Salary = 82500m
                        },
                        new
                        {
                            Id = 86,
                            Department = "Finance",
                            Designation = "Analyst",
                            Email = "employee86@example.com",
                            JoiningDate = new DateTime(2022, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 86",
                            Salary = 83000m
                        },
                        new
                        {
                            Id = 87,
                            Department = "Business",
                            Designation = "Consultant",
                            Email = "employee87@example.com",
                            JoiningDate = new DateTime(2022, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 87",
                            Salary = 83500m
                        },
                        new
                        {
                            Id = 88,
                            Department = "Consulting",
                            Designation = "Intern",
                            Email = "employee88@example.com",
                            JoiningDate = new DateTime(2022, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 88",
                            Salary = 84000m
                        },
                        new
                        {
                            Id = 89,
                            Department = "Operations",
                            Designation = "Lead",
                            Email = "employee89@example.com",
                            JoiningDate = new DateTime(2022, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 89",
                            Salary = 84500m
                        },
                        new
                        {
                            Id = 90,
                            Department = "Sales",
                            Designation = "Manager",
                            Email = "employee90@example.com",
                            JoiningDate = new DateTime(2022, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 90",
                            Salary = 85000m
                        },
                        new
                        {
                            Id = 91,
                            Department = "IT",
                            Designation = "Developer",
                            Email = "employee91@example.com",
                            JoiningDate = new DateTime(2022, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 91",
                            Salary = 85500m
                        },
                        new
                        {
                            Id = 92,
                            Department = "Marketing",
                            Designation = "Designer",
                            Email = "employee92@example.com",
                            JoiningDate = new DateTime(2022, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 92",
                            Salary = 86000m
                        },
                        new
                        {
                            Id = 93,
                            Department = "Customer Service",
                            Designation = "Support",
                            Email = "employee93@example.com",
                            JoiningDate = new DateTime(2022, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 93",
                            Salary = 86500m
                        },
                        new
                        {
                            Id = 94,
                            Department = "Human Resources",
                            Designation = "HR",
                            Email = "employee94@example.com",
                            JoiningDate = new DateTime(2022, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 94",
                            Salary = 87000m
                        },
                        new
                        {
                            Id = 95,
                            Department = "Finance",
                            Designation = "Accountant",
                            Email = "employee95@example.com",
                            JoiningDate = new DateTime(2022, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 95",
                            Salary = 87500m
                        },
                        new
                        {
                            Id = 96,
                            Department = "Business",
                            Designation = "Analyst",
                            Email = "employee96@example.com",
                            JoiningDate = new DateTime(2022, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 96",
                            Salary = 88000m
                        },
                        new
                        {
                            Id = 97,
                            Department = "Consulting",
                            Designation = "Consultant",
                            Email = "employee97@example.com",
                            JoiningDate = new DateTime(2022, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 97",
                            Salary = 88500m
                        },
                        new
                        {
                            Id = 98,
                            Department = "Operations",
                            Designation = "Intern",
                            Email = "employee98@example.com",
                            JoiningDate = new DateTime(2022, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 98",
                            Salary = 89000m
                        },
                        new
                        {
                            Id = 99,
                            Department = "Sales",
                            Designation = "Lead",
                            Email = "employee99@example.com",
                            JoiningDate = new DateTime(2022, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 99",
                            Salary = 89500m
                        },
                        new
                        {
                            Id = 100,
                            Department = "IT",
                            Designation = "Manager",
                            Email = "employee100@example.com",
                            JoiningDate = new DateTime(2022, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Employee 100",
                            Salary = 90000m
                        });
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
